name: cinemax
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  pinput: ^4.0.0
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  lottie: ^3.1.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.4.1
  loading_indicator: ^3.1.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2


 


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^3.0.0
 

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/
  fonts:
    - family: MR
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: MM
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: MSB
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
