name: cinemax
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 
  intl: ^0.18.1
  animated_theme_switcher: ^2.0.10
  shimmer: ^3.0.0
  pinput: ^4.0.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  lottie: ^3.1.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.4.1
  loading_indicator: ^3.1.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

  hive_flutter: ^1.1.0
  hive: ^2.2.3

  dropdown_button2: ^2.3.9
  connectivity_plus: ^5.0.2

  image_picker: ^1.0.7
  path_provider: ^2.1.2

  flutter_rating_bar: ^4.0.1

  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5

  video_player: ^2.8.3
  flick_video_player: ^0.7.0
  flutter_file_downloader: ^1.2.1

  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.21

  cupertino_icons: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

 
 

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/
    - assets/
  fonts:
    - family: MR
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: MM
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: MSB
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
    
