// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOZWnwz8dgZbr3aa5QSJp26i6TfuUAnWM',
    appId: '1:295736389256:web:f4e37603c3556174f3f93d',
    messagingSenderId: '295736389256',
    projectId: 'cinemax-42101',
    authDomain: 'cinemax-42101.firebaseapp.com',
    storageBucket: 'cinemax-42101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgp7unnwBIo4i7rm5Hd2mH61ihXxvwFE',
    appId: '1:295736389256:android:76981e09258d8d76f3f93d',
    messagingSenderId: '295736389256',
    projectId: 'cinemax-42101',
    storageBucket: 'cinemax-42101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6y36uB7UaqRcjBdfrTveLinkG4o76GA',
    appId: '1:295736389256:ios:cf96df17b953a478f3f93d',
    messagingSenderId: '295736389256',
    projectId: 'cinemax-42101',
    storageBucket: 'cinemax-42101.appspot.com',
    iosBundleId: 'com.example.cinemax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_6y36uB7UaqRcjBdfrTveLinkG4o76GA',
    appId: '1:295736389256:ios:92c6c0095c2884abf3f93d',
    messagingSenderId: '295736389256',
    projectId: 'cinemax-42101',
    storageBucket: 'cinemax-42101.appspot.com',
    iosBundleId: 'com.example.cinemax.RunnerTests',
  );
}
